// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BossBattleAttackPointsPromoCodeTyped
 */
export interface BossBattleAttackPointsPromoCodeTyped {
    /**
     * 
     * @type {string}
     * @memberof BossBattleAttackPointsPromoCodeTyped
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof BossBattleAttackPointsPromoCodeTyped
     */
    platform: string;
    /**
     * 
     * @type {string}
     * @memberof BossBattleAttackPointsPromoCodeTyped
     */
    readonly img: string;
    /**
     * 
     * @type {number}
     * @memberof BossBattleAttackPointsPromoCodeTyped
     */
    attackPoints: number;
    /**
     * 
     * @type {string}
     * @memberof BossBattleAttackPointsPromoCodeTyped
     */
    resourcetype: string;
}

/**
 * Check if a given object implements the BossBattleAttackPointsPromoCodeTyped interface.
 */
export function instanceOfBossBattleAttackPointsPromoCodeTyped(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "platform" in value;
    isInstance = isInstance && "img" in value;
    isInstance = isInstance && "attackPoints" in value;
    isInstance = isInstance && "resourcetype" in value;

    return isInstance;
}

export function BossBattleAttackPointsPromoCodeTypedFromJSON(json: any): BossBattleAttackPointsPromoCodeTyped {
    return BossBattleAttackPointsPromoCodeTypedFromJSONTyped(json, false);
}

export function BossBattleAttackPointsPromoCodeTypedFromJSONTyped(json: any, ignoreDiscriminator: boolean): BossBattleAttackPointsPromoCodeTyped {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'platform': json['platform'],
        'img': json['img'],
        'attackPoints': json['attack_points'],
        'resourcetype': json['resourcetype'],
    };
}

export function BossBattleAttackPointsPromoCodeTypedToJSON(value?: BossBattleAttackPointsPromoCodeTyped | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'platform': value.platform,
        'attack_points': value.attackPoints,
        'resourcetype': value.resourcetype,
    };
}

