// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatOnline
 */
export interface ChatOnline {
    /**
     * 
     * @type {number}
     * @memberof ChatOnline
     */
    online: number;
}

/**
 * Check if a given object implements the ChatOnline interface.
 */
export function instanceOfChatOnline(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "online" in value;

    return isInstance;
}

export function ChatOnlineFromJSON(json: any): ChatOnline {
    return ChatOnlineFromJSONTyped(json, false);
}

export function ChatOnlineFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatOnline {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'online': json['online'],
    };
}

export function ChatOnlineToJSON(value?: ChatOnline | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'online': value.online,
    };
}

