// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatCooldown
 */
export interface ChatCooldown {
    /**
     * 
     * @type {number}
     * @memberof ChatCooldown
     */
    cooldown: number;
}

/**
 * Check if a given object implements the ChatCooldown interface.
 */
export function instanceOfChatCooldown(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cooldown" in value;

    return isInstance;
}

export function ChatCooldownFromJSON(json: any): ChatCooldown {
    return ChatCooldownFromJSONTyped(json, false);
}

export function ChatCooldownFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCooldown {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cooldown': json['cooldown'],
    };
}

export function ChatCooldownToJSON(value?: ChatCooldown | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cooldown': value.cooldown,
    };
}

