// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailChangeResponse
 */
export interface EmailChangeResponse {
    /**
     * 
     * @type {string}
     * @memberof EmailChangeResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof EmailChangeResponse
     */
    access: string;
    /**
     * 
     * @type {string}
     * @memberof EmailChangeResponse
     */
    refresh: string;
}

/**
 * Check if a given object implements the EmailChangeResponse interface.
 */
export function instanceOfEmailChangeResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "access" in value;
    isInstance = isInstance && "refresh" in value;

    return isInstance;
}

export function EmailChangeResponseFromJSON(json: any): EmailChangeResponse {
    return EmailChangeResponseFromJSONTyped(json, false);
}

export function EmailChangeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailChangeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'access': json['access'],
        'refresh': json['refresh'],
    };
}

export function EmailChangeResponseToJSON(value?: EmailChangeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'access': value.access,
        'refresh': value.refresh,
    };
}

