// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GamelightInvoiceRequest
 */
export interface GamelightInvoiceRequest {
    /**
     * 
     * @type {number}
     * @memberof GamelightInvoiceRequest
     */
    orderId: number;
    /**
     * 
     * @type {number}
     * @memberof GamelightInvoiceRequest
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof GamelightInvoiceRequest
     */
    userId: number;
}

/**
 * Check if a given object implements the GamelightInvoiceRequest interface.
 */
export function instanceOfGamelightInvoiceRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "orderId" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function GamelightInvoiceRequestFromJSON(json: any): GamelightInvoiceRequest {
    return GamelightInvoiceRequestFromJSONTyped(json, false);
}

export function GamelightInvoiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamelightInvoiceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderId': json['order_id'],
        'amount': json['amount'],
        'userId': json['user_id'],
    };
}

export function GamelightInvoiceRequestToJSON(value?: GamelightInvoiceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order_id': value.orderId,
        'amount': value.amount,
        'user_id': value.userId,
    };
}

