// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoldRewardTyped
 */
export interface GoldRewardTyped {
    /**
     * 
     * @type {number}
     * @memberof GoldRewardTyped
     */
    bullcoins: number;
    /**
     * 
     * @type {string}
     * @memberof GoldRewardTyped
     */
    resourcetype: string;
}

/**
 * Check if a given object implements the GoldRewardTyped interface.
 */
export function instanceOfGoldRewardTyped(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bullcoins" in value;
    isInstance = isInstance && "resourcetype" in value;

    return isInstance;
}

export function GoldRewardTypedFromJSON(json: any): GoldRewardTyped {
    return GoldRewardTypedFromJSONTyped(json, false);
}

export function GoldRewardTypedFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoldRewardTyped {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bullcoins': json['bullcoins'],
        'resourcetype': json['resourcetype'],
    };
}

export function GoldRewardTypedToJSON(value?: GoldRewardTyped | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bullcoins': value.bullcoins,
        'resourcetype': value.resourcetype,
    };
}

