// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LanguageF93Enum } from './LanguageF93Enum';
import {
    LanguageF93EnumFromJSON,
    LanguageF93EnumFromJSONTyped,
    LanguageF93EnumToJSON,
} from './LanguageF93Enum';

/**
 * 
 * @export
 * @interface LanguageFull
 */
export interface LanguageFull {
    /**
     * 
     * @type {LanguageF93Enum}
     * @memberof LanguageFull
     */
    readonly code: LanguageF93Enum;
    /**
     * 
     * @type {string}
     * @memberof LanguageFull
     */
    readonly name: string;
}

/**
 * Check if a given object implements the LanguageFull interface.
 */
export function instanceOfLanguageFull(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function LanguageFullFromJSON(json: any): LanguageFull {
    return LanguageFullFromJSONTyped(json, false);
}

export function LanguageFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguageFull {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': LanguageF93EnumFromJSON(json['code']),
        'name': json['name'],
    };
}

export function LanguageFullToJSON(value?: LanguageFull | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

