// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentRedirectTyped
 */
export interface PaymentRedirectTyped {
    /**
     * 
     * @type {string}
     * @memberof PaymentRedirectTyped
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRedirectTyped
     */
    url: string;
}

/**
 * Check if a given object implements the PaymentRedirectTyped interface.
 */
export function instanceOfPaymentRedirectTyped(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function PaymentRedirectTypedFromJSON(json: any): PaymentRedirectTyped {
    return PaymentRedirectTypedFromJSONTyped(json, false);
}

export function PaymentRedirectTypedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRedirectTyped {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'url': json['url'],
    };
}

export function PaymentRedirectTypedToJSON(value?: PaymentRedirectTyped | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'url': value.url,
    };
}

