// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PUBGMinWithdrawal
 */
export interface PUBGMinWithdrawal {
    /**
     * 
     * @type {number}
     * @memberof PUBGMinWithdrawal
     */
    priceBullcoins: number;
}

/**
 * Check if a given object implements the PUBGMinWithdrawal interface.
 */
export function instanceOfPUBGMinWithdrawal(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "priceBullcoins" in value;

    return isInstance;
}

export function PUBGMinWithdrawalFromJSON(json: any): PUBGMinWithdrawal {
    return PUBGMinWithdrawalFromJSONTyped(json, false);
}

export function PUBGMinWithdrawalFromJSONTyped(json: any, ignoreDiscriminator: boolean): PUBGMinWithdrawal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'priceBullcoins': json['price_bullcoins'],
    };
}

export function PUBGMinWithdrawalToJSON(value?: PUBGMinWithdrawal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'price_bullcoins': value.priceBullcoins,
    };
}

