// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReactionsCount
 */
export interface ReactionsCount {
    /**
     * 
     * @type {string}
     * @memberof ReactionsCount
     */
    code: string;
    /**
     * 
     * @type {number}
     * @memberof ReactionsCount
     */
    count: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReactionsCount
     */
    isReacted: boolean;
}

/**
 * Check if a given object implements the ReactionsCount interface.
 */
export function instanceOfReactionsCount(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "isReacted" in value;

    return isInstance;
}

export function ReactionsCountFromJSON(json: any): ReactionsCount {
    return ReactionsCountFromJSONTyped(json, false);
}

export function ReactionsCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReactionsCount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'count': json['count'],
        'isReacted': json['is_reacted'],
    };
}

export function ReactionsCountToJSON(value?: ReactionsCount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'count': value.count,
        'is_reacted': value.isReacted,
    };
}

