// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SelectActiveCountryRequest
 */
export interface SelectActiveCountryRequest {
    /**
     * 
     * @type {number}
     * @memberof SelectActiveCountryRequest
     */
    countryId: number;
}

/**
 * Check if a given object implements the SelectActiveCountryRequest interface.
 */
export function instanceOfSelectActiveCountryRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "countryId" in value;

    return isInstance;
}

export function SelectActiveCountryRequestFromJSON(json: any): SelectActiveCountryRequest {
    return SelectActiveCountryRequestFromJSONTyped(json, false);
}

export function SelectActiveCountryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectActiveCountryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'countryId': json['country_id'],
    };
}

export function SelectActiveCountryRequestToJSON(value?: SelectActiveCountryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country_id': value.countryId,
    };
}

