// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SellInventoryBatchRequest
 */
export interface SellInventoryBatchRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof SellInventoryBatchRequest
     */
    ids: Array<number>;
}

/**
 * Check if a given object implements the SellInventoryBatchRequest interface.
 */
export function instanceOfSellInventoryBatchRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ids" in value;

    return isInstance;
}

export function SellInventoryBatchRequestFromJSON(json: any): SellInventoryBatchRequest {
    return SellInventoryBatchRequestFromJSONTyped(json, false);
}

export function SellInventoryBatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SellInventoryBatchRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ids': json['ids'],
    };
}

export function SellInventoryBatchRequestToJSON(value?: SellInventoryBatchRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ids': value.ids,
    };
}

