// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleCaseTyped
 */
export interface SimpleCaseTyped {
    /**
     * 
     * @type {number}
     * @memberof SimpleCaseTyped
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleCaseTyped
     */
    img: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleCaseTyped
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof SimpleCaseTyped
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleCaseTyped
     */
    resourcetype: string;
}

/**
 * Check if a given object implements the SimpleCaseTyped interface.
 */
export function instanceOfSimpleCaseTyped(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "img" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "resourcetype" in value;

    return isInstance;
}

export function SimpleCaseTypedFromJSON(json: any): SimpleCaseTyped {
    return SimpleCaseTypedFromJSONTyped(json, false);
}

export function SimpleCaseTypedFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleCaseTyped {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'img': json['img'],
        'name': json['name'],
        'price': json['price'],
        'resourcetype': json['resourcetype'],
    };
}

export function SimpleCaseTypedToJSON(value?: SimpleCaseTyped | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'img': value.img,
        'name': value.name,
        'price': value.price,
        'resourcetype': value.resourcetype,
    };
}

