// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TakeRewardRequest
 */
export interface TakeRewardRequest {
    /**
     * 
     * @type {number}
     * @memberof TakeRewardRequest
     */
    levelId: number;
}

/**
 * Check if a given object implements the TakeRewardRequest interface.
 */
export function instanceOfTakeRewardRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "levelId" in value;

    return isInstance;
}

export function TakeRewardRequestFromJSON(json: any): TakeRewardRequest {
    return TakeRewardRequestFromJSONTyped(json, false);
}

export function TakeRewardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TakeRewardRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'levelId': json['level_id'],
    };
}

export function TakeRewardRequestToJSON(value?: TakeRewardRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'level_id': value.levelId,
    };
}

