// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TranslationProject
 */
export interface TranslationProject {
    /**
     * * `None` - None
     * @type {string}
     * @memberof TranslationProject
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TranslationProject
     */
    name: string;
}

/**
 * Check if a given object implements the TranslationProject interface.
 */
export function instanceOfTranslationProject(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function TranslationProjectFromJSON(json: any): TranslationProject {
    return TranslationProjectFromJSONTyped(json, false);
}

export function TranslationProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranslationProject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function TranslationProjectToJSON(value?: TranslationProject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

