// @ts-nocheck
/* eslint-disable */
/**
 * Bulldrop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TranslationKey
 */
export interface TranslationKey {
    /**
     * 
     * @type {number}
     * @memberof TranslationKey
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TranslationKey
     */
    name: string;
}

/**
 * Check if a given object implements the TranslationKey interface.
 */
export function instanceOfTranslationKey(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function TranslationKeyFromJSON(json: any): TranslationKey {
    return TranslationKeyFromJSONTyped(json, false);
}

export function TranslationKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranslationKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function TranslationKeyToJSON(value?: TranslationKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

